exports.CONSENSUS = {
  RAFT: 'raft',
  ISTANBUL: 'istanbul'
}

exports.NODE_ROLE = {
  COORDINATOR: 'coordinator',
  NONCOORDINATOR: 'non-coordinator',
  DYNAMIC_PEER: 'dynamicPeer'
}

const FOLDER_QUORUM = 'quorum';
const FOLDER_BLOCKCHAIN = `${FOLDER_QUORUM}/blockchain`;
const FOLDER_GETH = 'geth';

const FOLDER_KEYSTORE = 'keystore';
const FILE_NODEKEY = 'nodekey';

exports.FOLDER_QUORUM = FOLDER_QUORUM;
exports.FOLDER_BLOCKCHAIN = FOLDER_BLOCKCHAIN;
exports.FOLDER_QUORUM_KEYSTORE = `${FOLDER_QUORUM}/${FOLDER_KEYSTORE}`;
exports.FILE_QUORUM_NODEKEY = `${FOLDER_QUORUM}/${FILE_NODEKEY}`;

exports.FOLDER_BLOCKCHAIN_GETH = `${FOLDER_BLOCKCHAIN}/${FOLDER_GETH}`;
exports.FOLDER_BLOCKCHAIN_KEYSTORE = `${FOLDER_BLOCKCHAIN}/${FOLDER_KEYSTORE}`;
exports.FILE_BLOCKCHAIN_NODEKEY = `${FOLDER_BLOCKCHAIN}/${FOLDER_GETH}/${FILE_NODEKEY}`;
exports.FILE_BLOCKCHAIN_IBFTVALIDATORADDRESS = `${FOLDER_BLOCKCHAIN}/validator_address`;
exports.FILE_BLOCKCHAIN_STATICNODES = `${FOLDER_BLOCKCHAIN}/static-nodes.json`;
exports.FILE_BLOCKCHAIN_GETHIPC = `${FOLDER_BLOCKCHAIN}/geth.ipc`;
exports.FILE_BLOCKCHAIN_GENESIS = `${FOLDER_BLOCKCHAIN}/quorum-genesis.json`;
exports.FILE_BLOCKCHAIN_NODEINFO = `${FOLDER_BLOCKCHAIN}/network_nodes_info.json`;

exports.BLOCKCHAIN_RPCPROVIDER_LOCALHOST = 'http://localhost:';
exports.BLOCKCHAIN_WSPROVIDER_LOCALHOST = 'ws://localhost:';

exports.SCRIPT_BLOCKCHAIN_STARTRAFTNODE = 'start-raft-node.sh';
exports.SCRIPT_BLOCKCHAIN_STARTISTANBULNODE = 'start-istanbul-node.sh';

const FOLDER_CONSTELLATION = 'constellation';

exports.FOLDER_CONSTELLATION = `${FOLDER_QUORUM}/${FOLDER_CONSTELLATION}`;
exports.FILE_CONSTELLATION_CONFIG = `${FOLDER_QUORUM}/constellation.config`;
exports.FILE_CONSTELLATION_PUBKEY = 'node.pub';
exports.FILE_CONSTELLATION_PRIVKEY = 'node.key';
exports.FILE_CONSTELLATION_ARCHPUBKEY = 'nodeArch.pub';
exports.FILE_CONSTELLATION_ARCHPRIVKEY = 'nodeArch.key';
exports.CONSTELLATION_HELPURL = 'https://github.com/ConsenSys/QuorumNetworkManager#upgrading-constellation';

exports.STDOUT_CONSTELLATIONGENKEY_LOCKKEYPAIR = 'Lock key pair';
exports.STDOUT_CONSTELLATIONVERSION_010 = 'Constellation Node 0.1.0';

const FOLDER_WHISPER = 'whisper';
const FOLDER_COMMUNICATIONNODE = `${FOLDER_QUORUM}/communication`;

exports.FOLDER_COMMUNICATIONNODE = FOLDER_COMMUNICATIONNODE;
exports.FOLDER_COMMNODE_GETH = `${FOLDER_COMMUNICATIONNODE}/${FOLDER_GETH}`;
exports.FILE_COMMNODE_NODEKEY = `${FOLDER_COMMUNICATIONNODE}/${FOLDER_GETH}/nodekey`;
exports.FILE_COMMNODE_GETHIPC = `${FOLDER_COMMUNICATIONNODE}/geth.ipc`;
exports.COMMNODE_RPCPROVIDER_LOCALHOST = 'http://localhost:';
exports.COMMNODE_WSPROVIDER_LOCALHOST = 'ws://localhost:';

exports.FILE_WHISPER_DEFAULTCOMMNODEKEY = `${FOLDER_WHISPER}/communication_node_key`;

exports.SCRIPT_WHISPER_STARTCOMMNODE = 'start-communication-node.sh';

exports.WHISPER_TOPIC_NETWORKMEMBERSHIP = 'NetworkMembership';
exports.WHISPER_TOPIC_GENESISCONFIG = 'GenesisConfig';
exports.WHISPER_TOPIC_STATICNODES = 'StaticNodes';
exports.WHISPER_TOPIC_ENODE = 'Enode';
exports.WHISPER_TOPIC_ETHER = 'Ether';
exports.WHISPER_TOPIC_NODEINFO = 'NodeInfo';

exports.EVENT_PEERHANDLER_NEWENODE = 'newEnode';

exports.STDOUT_NEWGETHACCOUNT_YOURNEWACCOUNT = 'Your new account';
exports.STDOUT_NEWGETHACCOUNT_REPEAT = 'Repeat';
exports.STDOUT_NEWGETHACCOUNT_ADDRESS = 'Address';
exports.STDERR_NEWGETHACCOUNT_NODEFAULTACC = 'No etherbase set and no accounts found as default';

exports.STDOUT_LISTGETHACCOUNT_ACCOUNT0 = 'Account #0';
exports.STDERR_LISTGETHACCOUNT_NODEFAULTACC = 'No etherbase set and no accounts found as default';

exports.NETWORKMEMBERSHIP= {
  ALLOWALL: 'allowAll',
  PERMISSIONEDNODES: 'permissionedNodes',
  ALLOW_ONLY_PREAUTH: 'allowOnlyPreAuth'
} 

exports.ISTANBUL_SETUP_OUTPUT = {
  VALIDATORS: 'validators',
  STATICNODES: 'static-nodes.json',
  GENESISJSON: 'genesis.json'
}

exports.ISTANBUL_SETUP_OUTPUT_VALIDATORS = {
  ADDRESS: 'Address',
  NODEINFO: 'NodeInfo',
  NODEKEY: 'Nodekey'
}

exports.ISTANBUL_SETUP_OUTPUT_GENESIS = {
  CONFIG: 'config'
}

// TODO set this in config
exports.RAFT_DEFAULTBALANCE = '0x235FADD81C2822BB3F07877973D50F28BF22A31BE8EE8000000000000000000';
exports.ISTANBUL_DEFAULTBALANCE = '0x235FADD81C2822BB3F07877973D50F28BF22A31BE8EE8000000000000000000';